version: "3.9"
secrets:
  DOG_API_TOKEN:
    file: ./compose_secrets.txt
  DOG_AGENT_BROKER_PASSWORD:
    file: ./compose_secrets.txt
  DOG_TRAINER_SMTP_PASSWORD:
    file: ./compose_secrets.txt
  DOG_TRAINER_DB_PASSWORD:
    file: ./compose_secrets.txt
  DOG_TRAINER_BROKER_PASSWORD:
    file: ./compose_secrets.txt

services:
  control:
    container_name: "control"
    build:
      context: "./control"
    ports:
      - "22:22"
    environment:
      - DOG_API_TOKEN=/var/run/dog_api_token
      - DOG_API_ENDPOINT=http://kong:8000/api/V2
      - TF_VAR_dog_api_token_docker=/var/run/dog_api_token
    secrets:
      - DOG_API_TOKEN
    depends_on:
      - "dog_trainer"
      - "dog_agent"
      - "dog_agent_ex"

  csc:
    container_name: "csc"
    build:
      context: "./csc"
    environment:
      - NGINX_PORT=9000
      - VIRTUAL_HOST=dog
      - VIRTUAL_PATH=/csc
      - PORT=9000
    ports:
     - "9000:9000"
  dog_agent_ex:
    container_name: "dog-agent-ex"
    build: 
      context: "./dog_agent_ex"
      dockerfile: Dockerfile.local_deploy
    depends_on:
      - "csc"
      - "dog_trainer"
      - "rabbitmq"
    cap_add:
      - NET_ADMIN
    environment:
      - SHELL=/bin/sh
    volumes:
      - ./dog_agent_ex_home:/root
  dog_agent:
    container_name: "dog-agent"
    build: 
      context: "./dog_agent"
      dockerfile: Dockerfile.local_deploy
    depends_on:
      - "csc"
      - "dog_trainer"
      - "rabbitmq"
    cap_add:
      - NET_ADMIN
    environment:
      - SHELL=/bin/sh
    volumes:
      - ./dog_agent_home:/root
    secrets:
      - DOG_AGENT_BROKER_PASSWORD
  nginx-proxy:
    container_name: "nginx-proxy"
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - DEFAULT_HOST=dog
    depends_on:
      - "kong"
      - "dog_park"
  dog_park:
    container_name: "dog-park"
    build: "./dog_park"
    environment:
      - NGINX_PORT=3030
      - REACT_APP_DOG_API_HOST=http://dog
      - VIRTUAL_HOST=dog
      - VIRTUAL_PATH=/
    depends_on:
      - "dog_trainer"
  dog_trainer:
    environment:
      - VIRTUAL_PORT=7070
      - VIRTUAL_HOST=dog
      - VIRTUAL_PATH=/api
    container_name: "dog-trainer"
    build: 
      context: "./dog_trainer"
      dockerfile: Dockerfile.local_deploy
    depends_on:
      - "csc"
      - "rethinkdb"
      - "rabbitmq"
    ports:
      - "7070:7070"
    volumes:
      - ./dog_trainer_home:/root
    secrets:
      - DOG_TRAINER_SMTP_PASSWORD
      - DOG_TRAINER_DB_PASSWORD
      - DOG_TRAINER_BROKER_PASSWORD

  kong:
    container_name: "kong"
    build:
      context: "./kong"
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=kong
      - VIRTUAL_PATH=/api
      - KONG_DATABASE=off
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
      - KONG_DECLARATIVE_CONFIG=/kong.yml
    depends_on:
      - "csc"
      - "dog_trainer"
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
  rethinkdb:
    container_name: "rethinkdb"
    image: "rethinkdb"
    ports:
      - "8080:8080"
      - "28015:28015"
  rabbitmq:
    container_name: "rabbitmq"
    build: ./rabbitmq
      #image: "rabbitmq:management"
    environment:
      - RABBITMQ_DEFAULT_VHOST=dog
    ports:
      - "5673:5673"
      - "15672:15672"
    depends_on:
      - "csc"
  flan:
    container_name: "flan"
    build:
      context: "./flan"
    environment:
      - NGINX_PORT=80
      - VIRTUAL_HOST=dog
      - VIRTUAL_PATH=/flan_api
