version: "3.9"
services:
  dog_agent:
    container_name: "dog_agent"
    build: "./dog_agent"
    ports:
      - "2222:2222"
    depends_on:
      - "dog_trainer"
      - "rabbitmq"
    cap_add:
      - NET_ADMIN
    environment:
      - SHELL=/bin/sh
  nginx-proxy:
    container_name: "dog_nginx_proxy"
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - DEFAULT_HOST=dog
  dog_park:
    container_name: "dog_park"
    build: "./dog_park"
    ports:
      - "3030:3030"
    environment:
      - NGINX_PORT=3030
      - REACT_APP_DOG_API_HOST=http://dog
      - VIRTUAL_HOST=dog
      - VIRTUAL_PATH=/
    depends_on:
      - "dog_trainer"
  dog_trainer:
    container_name: "dog_trainer"
    build: ./dog_trainer
    ports:
      - "7070:7070"
    environment:
      - VIRTUAL_HOST=dog
      - VIRTUAL_PATH=/api
    depends_on:
      - "rethinkdb"
      - "rabbitmq"
  rethinkdb:
    container_name: "rethinkdb"
    image: "rethinkdb"
    ports:
      - "8080:8080"
  rabbitmq:
    container_name: "rabbitmq"
    image: "rabbitmq:management"
    environment:
      - RABBITMQ_DEFAULT_VHOST=dog
    ports:
      - "15672:15672"
