version: "3.9"
services:
  csc:
    container_name: "csc"
    build:
      context: "./csc"
    environment:
      - NGINX_PORT=8000
      - VIRTUAL_HOST=dog
      - VIRTUAL_PATH=/csc
      - PORT=8000
    ports:
     - "8000:8000"
        #volumes:
        #  - ./csc_tmp:/tmp
  dog_agent_ex:
    container_name: "dog-agent-ex"
    build: 
      context: "./dog_agent_ex"
      dockerfile: Dockerfile.local_deploy
    depends_on:
      - "csc"
      - "dog_trainer"
      - "rabbitmq"
    cap_add:
      - NET_ADMIN
    environment:
      - SHELL=/bin/sh
    volumes:
      - ./dog_agent_ex_home:/root
  dog_agent:
    container_name: "dog-agent"
    build: 
      context: "./dog_agent"
      dockerfile: Dockerfile.local_deploy
    depends_on:
      - "csc"
      - "dog_trainer"
      - "rabbitmq"
    cap_add:
      - NET_ADMIN
    environment:
      - SHELL=/bin/sh
    volumes:
      - ./dog_agent_home:/root
  nginx-proxy:
    container_name: "dog-nginx-proxy"
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - DEFAULT_HOST=dog
  dog_park:
    container_name: "dog-park"
    build: "./dog_park"
    environment:
      - NGINX_PORT=3030
      - REACT_APP_DOG_API_HOST=http://dog
      - VIRTUAL_HOST=dog
      - VIRTUAL_PATH=/
    depends_on:
      - "dog_trainer"
  dog_trainer:
    container_name: "dog-trainer"
    build: 
      context: "./dog_trainer"
      dockerfile: Dockerfile.local_deploy
    environment:
      - VIRTUAL_HOST=dog
      - VIRTUAL_PATH=/api
    depends_on:
      - "csc"
      - "rethinkdb"
      - "rabbitmq"
    volumes:
      - ./dog_trainer_home:/root
  rethinkdb:
    container_name: "rethinkdb"
    image: "rethinkdb"
    ports:
      - "8080:8080"
  rabbitmq:
    container_name: "rabbitmq"
    build: ./rabbitmq
      #image: "rabbitmq:management"
    environment:
      - RABBITMQ_DEFAULT_VHOST=dog
    ports:
      - "5673:5673"
      - "15672:15672"
    depends_on:
      - "csc"
